### ISSUE TITLE
Suggestions et bugs

### ISSUE THREAD

**Issue by ghost** [Joffrey4/CompressedBlocks#1]
Bonjour, est ce que tu pourrais ajouter les blocs de planches en bois compressé ? On a souvent l'habitude de transformer les bûches en planches et du coup après sa prend énormément de place dans les coffres.
Et aussi je trouve dommage que lorsque l'on casse un bloc compressé, on récupère les 9 blocs qui ont permis de le créer, ce serait mieux que l'on récupère simplement le bloc.

**Comment by Joffreybvn** [comment]
Salut,

Je te rejoins totalement sur les planches de bois. Et je les ajouterai au mod très prochainement.

Cependant, je ne modifierai pas le drop des blocs compressés. D'abord parce que, dans son état actuel, ce mod ne rajoute pas des blocs de construction. Ce sont des blocs destinés à stocker, et pas à être posés ni détruits régulièrement. Et je préfère qu'ils droppent 9 petits blocs car selon moi, si tu attaches 9 blocs ensemble, et que tu les détruits, alors tu détaches les blocs.

Mais, je comprends que pour utiliser ces blocs en décoration, ce n'est pas pratique de devoir les recrafter à chaque fois. Du coup, je pensais ajouter un nouveau craft qui consisterait à faire chauffer un bloc compressé dans un four pour le "solidifier". Un peu comme la Cobblestone qui redevient de la Stone quand tu la chauffes. 

Ce nouveau bloc pourrait toujours être décompressé, mais lorsque tu le casses, comme il est solide, il reste en entier. Et il aurait la même texture que le bloc compressé normal.

Je te laisse me dire ce que tu en penses, et si tu as d'autres idées, n'hésite pas !

**Comment by Joffreybvn** [comment]
J'ai ajouté les planches. Tu peux télécharger la nouvelle version du mod en [cliquant directement ici](https://github.com/Joffrey4/CompressedBlocks/releases/download/v1.10.2-1.1/compressedBlocksMod-1.10.2-1.1.jar).

**Comment by ghost** [comment]
Salut,
Super idée pour les blocs compressés chauffés ! Par contre il faudrait peut être changé légèrement la texture pour éviter de les confondre avec des blocs normaux. Et tu pourrais même créer un four spécialement pour faire chauffer les blocs, ou il faudrait utiliser de la lave pour que sa fonctionne. De plus, cela permettrait de se différencier un peu d'extraUtils :)

Petite liste de bug que j'ai trouvé :
-Les blocs compressés de terre, sable et sable rouge, soulsand (sable des âmes) ne se cassent pas correctement lorsque l'on utilise la pelle, c'est aussi long de miner les blocs à la main qu'à la pelle peu importe si celle-ci est en diamant, fer ou pierre.
-Le sable des âme compressé ne ralentit pas le joueur lorsqu'il marche dessus (je sais pas si c'est vraiment un bug)
-Lorsque l'on clic droit avec le briquet sur un bloc de netherrack, une flamme s'allume mais s'éteint à un moment (normalement elle devrait rester indéfiniment).
-Lorsqu'on clic avec la molette de la souris sur un bloc de sable rouge compressé, un bloc d'andésite, granite ou diorite compressé pour en obtenir un exemplaire en créatif, on se retrouve avec un bloc qui à une texture bugué :
![2017-05-21_12 31 53](https://cloud.githubusercontent.com/assets/25375924/26283103/8b35ee08-3e21-11e7-84c2-b02952d011cd.png)
![2017-05-21_12 31 56](https://cloud.githubusercontent.com/assets/25375924/26283104/8da11e10-3e21-11e7-8ed0-e237cbbbd4d4.png)
![2017-05-21_12 34 53](https://cloud.githubusercontent.com/assets/25375924/26283120/ebaa0e68-3e21-11e7-8222-27497201136b.png)
![2017-05-21_12 34 54](https://cloud.githubusercontent.com/assets/25375924/26283121/edbf915a-3e21-11e7-901c-8f7b67969a34.png)
![2017-05-21_12 34 55](https://cloud.githubusercontent.com/assets/25375924/26283123/efbd81f6-3e21-11e7-9e56-62adf29856e2.png)

**Comment by Joffreybvn** [comment]
Merci pour cette liste détaillée. La prochaine mise à jour corrigera ces bugs.

Concernant l'ajout de fonctionnalités comme celles que tu as proposé, je les implémenterai dans des add-ons afin que le mod de base ne soit pas surchagé. Et que le joueur qui veut simplement de la compression ne soit pas parasité par des éléments fantaisistes qu'il n’appréciera pas.

Ainsi, le joueur qui a le mod de base pourra ensuite choisir de télécharger l'add-on "bloc de décoration", pour obtenir les blocs dont nous avons parlé plus haut, ainsi que le four. Et il pourra également ajouter l'add-on "surcompression", qui intégrerait la compression de blocs déjà compressés.

Mais ceci est un exemple. J'attend un moment pour récolter toutes les idées, et ensuite je les implémenterai.
Si tu as d'autres idées donc, n'hésite pas !

**Comment by ghost** [comment]
Si tu veux une idée pour ton addon "surcompression" tu pourrais mettre une machine qui marcherait au charbon ou au RF (avec d'autres mods) et cette machine permettrait de compresser automatiquement les blocs. Mais celle-ci marcherait surtout si la compression va loin, par exemple un bloc de pierre compressé 10 fois :)

**Comment by Joffreybvn** [comment]
La version 1.3 corrigeant tous ces bugs est [téléchargeable par ici](https://github.com/Joffrey4/CompressedBlocks/releases/tag/v1.11.2-1.3).

Pour que les choses restent claires, je ferme ce billet. Si tu constates d'autres bugs, où que tu as d'autres idées, n'hésite pas à en ouvrir un nouveau.
